### ISSUE TITLE
lcd12864 pin link

### ISSUE THREAD

**Issue by cx4** [nquest/micropython-st7565#1]
[![Mx2qWF.md.jpg](https://s2.ax1x.com/2019/11/26/Mx2qWF.md.jpg)](https://imgchr.com/i/Mx2qWF)
I have an LCD screen, which is driven by st7565, but I don't know how to connect the line with micropython

**Comment by cx4** [comment]
pin 
RST CS D7 D6 D5 D4 D3 D2 D1 D0 WR RD RS _ VCC GND

**Comment by nquest** [comment]
This is an 8-bit bi-directional data bus that connects to an 8-bit or 16-bit standard MPU data bus. When the serial interface (SPI-4) is selected (P/S = “L”) : D7 : serial data input (SI)  ; D6  : the serial clock input (SCL). D0 to D5 should be connected to VDD or floating. When the chip select is not active, D0 to D7 are set to high impedance.

**Comment by nquest** [comment]
You need to find a P/S pin. Maybe as solder jumper, maybe on ribbon cable.
